### ISSUE TITLE
Please reopen #1

### ISSUE THREAD

**Issue by stephanvierkant** [phpsed/cache#2]
It's a bit rude to close #1 without the possibility to have a discussion about it. I'd like to contribute, but it feels like it's not appreciated at all. If so, please make this a private repository (or disable PR's and issues).

I decided to use an existing widely used Code Styling to prevent arbitrary personal preferences, but I understand if you don't like some of it (I personally don't like `if (! $variable)` either).

**Comment by phpsed** [comment]
Ok, I reopened #1's discussion.

**Comment by stephanvierkant** [comment]
You didn't reopen it, you only unblocked conversation. But more important: do you accept contributions in the first place?

**Comment by phpsed** [comment]
I do accept them but as this is still my repo, I don't have to merge things I don't feel right for my repo.

**Comment by stephanvierkant** [comment]
Of course, but it's also my spare time. And I don't want to spend time on projects where I don't feel that contributions are very welcome.

My suggestion: use a style guide and be explicit about your personal preferences (that's where `phpcs.xml` is for!) and enforce it using automated tests. Closing PR's because you don't like the spaces and line breaks is very rude.

**Comment by phpsed** [comment]
So, it would be better to merge even if I didn't like it? that's not how it should work

**Comment by stephanvierkant** [comment]
No, don't merge it as long as it doesn't meet your requirements (in this case: the right code style).
